<h2 align='center'>NLP Tutorial: Text Representation - Bag Of Words (BOW)</h2>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("spam.csv")
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [4]:
df['spam'] = df['Category'].apply(lambda x: 1 if x =='spam' else 0)

In [5]:
df.shape

(5572, 3)

In [6]:
df.head()

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

<h3>Train test split</h3>

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [8]:
X_train.shape

(4457,)

In [9]:
X_test.shape

(1115,)

In [10]:
type(X_train)

pandas.core.series.Series

In [11]:
X_train[:4]

2334                    What happen to her tell the truth
5247    Gud ni8 dear..slp well..take care..swt dreams....
1619    The 2 oz guy is being kinda flaky but one frie...
3008    Ah you see. You have to be in the lingo. I wil...
Name: Message, dtype: object

In [25]:
X_train.loc[2334]

'What happen to her tell the truth'

In [12]:
type(y_train)

pandas.core.series.Series

In [13]:
y_train[:4]

2334    0
5247    0
1619    0
3008    0
Name: spam, dtype: int64

In [14]:
type(X_train.values)

numpy.ndarray

<h3>Create bag of words representation using CountVectorizer</h3>

In [15]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59605 stored elements and shape (4457, 7757)>

In [16]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], shape=(7757,))

In [17]:
X_train_cv.shape

(4457, 7757)

In [22]:
v.get_feature_names_out()[7481]

'what'

In [19]:
v.vocabulary_

{'what': 7481,
 'happen': 3334,
 'to': 6936,
 'her': 3420,
 'tell': 6753,
 'the': 6811,
 'truth': 7064,
 'gud': 3270,
 'ni8': 4762,
 'dear': 2196,
 'slp': 6236,
 'well': 7459,
 'take': 6690,
 'care': 1658,
 'swt': 6665,
 'dreams': 2449,
 'muah': 4632,
 'oz': 5035,
 'guy': 3289,
 'is': 3763,
 'being': 1308,
 'kinda': 3958,
 'flaky': 2881,
 'but': 1580,
 'one': 4934,
 'friend': 3004,
 'interested': 3721,
 'in': 3659,
 'picking': 5189,
 'up': 7181,
 'lt': 4256,
 'gt': 3264,
 'worth': 7614,
 'tonight': 6972,
 'if': 3618,
 'possible': 5315,
 'ah': 869,
 'you': 7717,
 'see': 5980,
 'have': 3366,
 'be': 1271,
 'lingo': 4141,
 'will': 7525,
 'let': 4098,
 'know': 3979,
 'wot': 7616,
 'on': 4930,
 'earth': 2512,
 'it': 3775,
 'when': 7488,
 'has': 3352,
 'finished': 2858,
 'making': 4334,
 'wonder': 7585,
 'how': 3536,
 'got': 3204,
 'online': 4938,
 'my': 4664,
 'love': 4233,
 'had': 3300,
 'gone': 3185,
 'net': 4740,
 'cafe': 1600,
 'did': 2300,
 'get': 3123,
 'your': 7722,
 'phone': 5174,
 'recharged': 5618,
 'were': 7468,
 'friends': 3005,
 'think': 6844,
 'of': 4889,
 'boytoy': 1475,
 'dont': 2410,
 'want': 7380,
 'hear': 3386,
 'anything': 1004,
 'piss': 5207,
 'talking': 6702,
 'someone': 6297,
 'that': 6807,
 'realise': 5587,
 'point': 5274,
 'this': 6853,
 'at': 1118,
 'now': 4839,
 'read': 5580,
 'backwards': 1194,
 'don': 2407,
 'can': 1632,
 'away': 1167,
 'for': 2937,
 'trek': 7042,
 'long': 4198,
 'with': 7555,
 'family': 2765,
 'town': 7009,
 'sorry': 6327,
 'no': 4791,
 'check': 1755,
 'his': 3450,
 'detailed': 2274,
 'message': 4456,
 'good': 3188,
 'morning': 4585,
 'shijutta': 6081,
 'great': 3238,
 'amp': 949,
 'successful': 6569,
 'day': 2184,
 'very': 7272,
 'happy': 3343,
 'babe': 1184,
 'woo': 7590,
 'hoo': 3497,
 'party': 5088,
 'dude': 2481,
 'pls': 5246,
 'give': 3151,
 'prometazine': 5437,
 'syrup': 6672,
 '5mls': 558,
 'then': 6825,
 'mins': 4497,
 'later': 4041,
 'feed': 2798,
 'lol': 4193,
 'wtf': 7641,
 'random': 5549,
 'btw': 1544,
 'lunch': 4269,
 'break': 1491,
 'mean': 4413,
 'confirmed': 1965,
 'tot': 6999,
 'they': 6837,
 'juz': 3898,
 'say': 5920,
 'oni': 4936,
 'ok': 4913,
 'by': 1595,
 'monday': 4564,
 'next': 4761,
 'week': 7442,
 'me': 4411,
 'full': 3039,
 'gist': 3149,
 'shhhhh': 6079,
 'nobody': 4794,
 'supposed': 6620,
 'cool': 2007,
 'll': 4168,
 'come': 1908,
 'like': 4124,
 'ish': 3766,
 'watching': 7405,
 'cartoon': 1677,
 'listening': 4155,
 'music': 4654,
 'eve': 2661,
 'go': 3167,
 'temple': 6761,
 'church': 1816,
 'about': 754,
 'imma': 3642,
 'definitely': 2227,
 'need': 4723,
 'restock': 5739,
 'before': 1296,
 'thanksgiving': 6801,
 'out': 5005,
 'home': 3486,
 'down': 2431,
 'within': 7558,
 'min': 4483,
 'accept': 769,
 'or': 4971,
 'am': 932,
 'begging': 1300,
 'change': 1726,
 'number': 4852,
 'he': 3377,
 'here': 3421,
 'all': 908,
 'night': 4772,
 'lemme': 4088,
 're': 5575,
 'around': 1073,
 'last': 4037,
 'chance': 1724,
 'claim': 1824,
 'ur': 7199,
 '150': 302,
 'discount': 2350,
 'vouchers': 7328,
 'today': 6943,
 'text': 6785,
 'shop': 6102,
 '85023': 676,
 'savamob': 5914,
 'offers': 4897,
 'mobile': 4543,
 'cs': 2097,
 'pobox84': 5266,
 'm263uz': 4287,
 '00': 0,
 'sub': 6551,
 '16': 313,
 'way': 7415,
 'should': 6114,
 'stay': 6461,
 'oh': 4908,
 'tomorrow': 6964,
 'not': 4824,
 'going': 3178,
 'theatre': 6815,
 'so': 6280,
 'wherever': 7494,
 'call': 1610,
 'where': 7492,
 'and': 961,
 'late': 4039,
 'da': 2146,
 'laptop': 4031,
 'there': 6830,
 'ring': 5776,
 'comes': 1910,
 'guys': 3290,
 'costumes': 2030,
 'gift': 3138,
 'their': 6818,
 'future': 3053,
 'yowifes': 7731,
 'hint': 3446,
 'deepest': 2219,
 'darkest': 2167,
 'fantasies': 2770,
 '09094646631': 244,
 'just': 3892,
 '60p': 570,
 'stop': 6492,
 'texts': 6794,
 '08712460324': 111,
 'nat': 4694,
 'rate': 5558,
 'networking': 4747,
 'job': 3848,
 'ill': 3629,
 'evening': 2664,
 'some': 6294,
 'ideas': 3612,
 'meeting': 4429,
 '0a': 255,
 'networks': 4748,
 'allow': 914,
 'companies': 1923,
 'bill': 1355,
 'sms': 6259,
 'are': 1051,
 'responsible': 5736,
 'suppliers': 6614,
 'as': 1088,
 'guarantee': 3267,
 'sell': 5999,
 'howz': 3542,
 'pain': 5047,
 'hope': 3504,
 'fine': 2853,
 'also': 924,
 'bringing': 1512,
 'galileo': 3064,
 'dobby': 2376,
 'we': 7420,
 'do': 2374,
 'medical': 4423,
 'missions': 4516,
 'nigeria': 4770,
 'spoke': 6400,
 'uncle': 7139,
 'john': 3854,
 'strongly': 6526,
 'feels': 2804,
 'sacrifice': 5865,
 'keep': 3926,
 'does': 2385,
 'beg': 1298,
 'listen': 4153,
 'make': 4330,
 'any': 996,
 'promises': 5441,
 'clear': 1839,
 'things': 6843,
 'easy': 2519,
 'please': 5238,
 'us': 7214,
 'work': 7599,
 'expecting': 2712,
 'help': 3409,
 'creativity': 2073,
 'stifled': 6478,
 'him': 3443,
 'part': 5082,
 'japanese': 3812,
 'proverb': 5457,
 'too': 6977,
 'none': 4807,
 'must': 4656,
 'indian': 3681,
 'version': 7270,
 'leave': 4075,
 'finally': 2848,
 'kerala': 3933,
 'doing': 2398,
 'strike': 6520,
 'against': 857,
 'hello': 3406,
 'handsome': 3326,
 'finding': 2851,
 'lazy': 4058,
 'working': 7603,
 'towards': 7008,
 'getting': 3131,
 'back': 1192,
 'mummy': 4643,
 'miss': 4510,
 'hi': 3433,
 'its': 3783,
 'kate': 3918,
 'bit': 1371,
 'bloody': 1401,
 'babyjontet': 1189,
 'txt': 7101,
 'xxx': 7667,
 'omw': 4929,
 'castor': 1685,
 'track': 7012,
 'lighters': 4121,
 'find': 2850,
 'urgent': 7203,
 'trying': 7066,
 'contact': 1985,
 'todays': 6944,
 'draw': 2445,
 'shows': 6127,
 'won': 7583,
 '800': 634,
 'prize': 5409,
 'guaranteed': 3268,
 '09050001808': 167,
 'from': 3020,
 'land': 4024,
 'line': 4137,
 'm95': 4292,
 'valid12hrs': 7243,
 'only': 4940,
 'noe': 4795,
 'she': 6069,
 'car': 1653,
 'lar': 4032,
 'wearing': 7426,
 'shorts': 6112,
 'nope': 4811,
 'tv': 7090,
 'bored': 1439,
 'boy': 1470,
 'bad': 1195,
 'positive': 5310,
 'negative': 4732,
 'why': 7509,
 'made': 4308,
 'wait': 7356,
 'hmmmm': 3465,
 'fake': 2756,
 'frnds': 3014,
 'money': 4566,
 'thts': 6884,
 'reffering': 5638,
 'member': 4440,
 'wit': 7554,
 'mail': 4322,
 'link': 4142,
 'vl': 7313,
 'credited': 2075,
 'rs': 5830,
 'il': 3627,
 'getiing': 3125,
 'acc': 766,
 'wen': 7462,
 'doesn': 2386,
 'class': 1832,
 'early': 2508,
 'thus': 6887,
 'shouldn': 6116,
 'smoke': 6255,
 'never': 4751,
 'invite': 3738,
 'anywhere': 1009,
 'winner': 7537,
 'been': 1292,
 'specially': 6367,
 'selected': 5993,
 'receive': 5609,
 '1000': 259,
 'holiday': 3481,
 'flights': 2889,
 'inc': 3661,
 'speak': 6361,
 'live': 4160,
 'operator': 4958,
 '0871277810910p': 115,
 '18': 318,
 'hey': 3430,
 'something': 6301,
 'came': 1628,
 'wun': 7649,
 'signing': 6155,
 'tmr': 6930,
 'hee': 3397,
 'missing': 4514,
 'plenty': 5243,
 'people': 5134,
 'msgs': 4621,
 'iam': 3593,
 'addicted': 809,
 'msging': 4618,
 'wrong': 7635,
 'bcoz': 1265,
 'sweet': 6651,
 'bslvyl': 1538,
 'cos': 2023,
 'was': 7393,
 'shopping': 6104,
 'wif': 7516,
 'darren': 2172,
 'jus': 3891,
 'called': 1616,
 'ask': 1096,
 'wat': 7400,
 'present': 5377,
 'wan': 7375,
 'lor': 4212,
 'started': 6449,
 'guessing': 3278,
 'who': 7503,
 'guessed': 3275,
 'sos': 6335,
 'amount': 948,
 'few': 2816,
 'hit': 3452,
 'fuck': 3028,
 'yes': 7700,
 'them': 6821,
 'investigate': 3736,
 'movies': 4606,
 'side': 6146,
 'open': 4952,
 'rebtel': 5604,
 'firefox': 2864,
 'loads': 4174,
 'put': 5495,
 'plus': 5249,
 'sign': 6150,
 'user': 7220,
 'name': 4680,
 'place': 5215,
 'show': 6121,
 'two': 7099,
 'numbers': 4853,
 'lower': 4246,
 'once': 4933,
 'pick': 5187,
 'pin': 5204,
 'display': 2358,
 'okay': 4914,
 'said': 5874,
 'problem': 5416,
 'protect': 5455,
 'yourself': 7727,
 'threats': 6870,
 'sib': 6142,
 'asks': 1101,
 'sensitive': 6015,
 'information': 3692,
 'passwords': 5097,
 'atm': 1123,
 'thru': 6881,
 'email': 2570,
 'share': 6063,
 'password': 5096,
 'anybody': 997,
 'really': 5594,
 'bhaji': 1345,
 'told': 6953,
 'kallis': 3908,
 'best': 1328,
 'cricketer': 2081,
 'after': 850,
 'sachin': 5862,
 'world': 7605,
 'tough': 7005,
 'princess': 5398,
 'every': 2670,
 'wish': 7547,
 'command': 1915,
 'sen': 6006,
 'means': 4415,
 'thought': 6865,
 'watch': 7401,
 'thats': 6810,
 'kind': 3957,
 'thing': 6842,
 'get4an18th': 3124,
 'loves': 4241,
 'much': 4633,
 'po': 5254,
 'de': 2190,
 'aha': 870,
 'other': 4996,
 'news': 4759,
 'hassling': 3356,
 'weed': 7441,
 'andres': 964,
 'haughaighgtujhyguj': 3360,
 'denying': 2254,
 'words': 7598,
 'yup': 7740,
 'www': 7650,
 'applausestore': 1023,
 'com': 1903,
 'monthlysubscription': 4576,
 '50p': 540,
 'msg': 4616,
 'max6': 4399,
 'month': 4574,
 'csc': 2099,
 'web': 7430,
 'age16': 860,
 '2stop': 413,
 'ever': 2669,
 'notice': 4830,
 'driving': 2461,
 'anyone': 1000,
 'slower': 6233,
 'than': 6796,
 'an': 957,
 'idiot': 3616,
 'everyone': 2674,
 'faster': 2777,
 'maniac': 4352,
 'haha': 3303,
 'den': 2246,
 'shld': 6095,
 'went': 7465,
 'gee': 3102,
 'nvm': 4861,
 'la': 4004,
 'kaiez': 3904,
 'dun': 2488,
 'mind': 4486,
 'goin': 3176,
 'jazz': 3819,
 'oso': 4994,
 'scared': 5929,
 'hiphop': 3448,
 'cant': 1644,
 'catch': 1688,
 'congrats': 1969,
 '3g': 455,
 'videophones': 7283,
 'yours': 7726,
 '09061744553': 202,
 'videochat': 7282,
 'wid': 7514,
 'mates': 4385,
 'play': 5229,
 'java': 3815,
 'games': 3069,
 'dload': 2371,
 'polyh': 5285,
 'noline': 4804,
 'rentl': 5691,
 'bx420': 1593,
 'ip4': 3747,
 '5we': 563,
 '150pm': 306,
 '645': 580,
 'wats': 7411,
 'opinion': 4959,
 'abt': 759,
 'character': 1732,
 'payasam': 5110,
 'rinu': 5781,
 'brings': 1513,
 'yeah': 7688,
 'aight': 877,
 'roommates': 5813,
 'snow': 6276,
 'weather': 7429,
 'ppl': 5336,
 'together': 6947,
 'friendships': 3008,
 'grow': 3258,
 'new': 4754,
 '08712400200': 101,
 'vodafone': 7315,
 'ending': 2587,
 '4882': 504,
 '350': 443,
 'award': 1165,
 'matches': 4383,
 '09064019014': 217,
 'office': 4898,
 'na': 4670,
 '1apple': 325,
 'doctor': 2381,
 '1tulsi': 340,
 'leaf': 4069,
 'cancer': 1639,
 '1lemon': 331,
 'fat': 2779,
 '1cup': 327,
 'milk': 4479,
 'bone': 1425,
 'problms': 5418,
 'litres': 4158,
 'watr': 7410,
 'diseases': 2354,
 'snd': 6270,
 'ths': 6882,
 'whom': 7505,
 'arun': 1087,
 'transfr': 7025,
 'amt': 954,
 'thanks': 6800,
 'ringtone': 5778,
 'order': 4979,
 'reference': 5635,
 't91': 6675,
 'charged': 1735,
 'gbp': 3095,
 'per': 5136,
 'unsubscribe': 7177,
 'anytime': 1006,
 'calling': 1622,
 'customer': 2132,
 'services': 6029,
 '09057039994': 174,
 'lover': 4238,
 'goes': 3173,
 'wake': 7360,
 'slave': 6211,
 'send': 6007,
 'teasing': 6740,
 'kiss': 3966,
 'across': 791,
 'sea': 5962,
 'virtual': 7303,
 'hug': 3556,
 'aiyar': 886,
 'poor': 5296,
 'support': 6617,
 'jia': 3843,
 'transaction': 7021,
 've': 7260,
 'sent': 6016,
 'latest': 4042,
 'project': 5434,
 'purity': 5487,
 'friendship': 3007,
 'between': 1337,
 'smiling': 6253,
 'reading': 5583,
 'forwarded': 2962,
 'seeing': 5982,
 'evng': 2681,
 'musthu': 4657,
 'done': 2408,
 'space': 6349,
 'gives': 3153,
 'everything': 2675,
 'remember': 5672,
 'furniture': 3050,
 'move': 4602,
 'lock': 4182,
 'locks': 4183,
 'key': 3937,
 'jenne': 3828,
 'still': 6480,
 'little': 4159,
 'experience': 2715,
 'understand': 7145,
 'american': 936,
 'voice': 7317,
 'yep': 7698,
 '30': 424,
 'ice': 3603,
 'age': 859,
 'free': 2983,
 'pa': 5036,
 'shall': 6055,
 'pickle': 5190,
 'sure': 6624,
 'whenever': 7489,
 'contacted': 1986,
 'our': 5002,
 'dating': 2179,
 'service': 6028,
 '09050000878': 164,
 'pobox45w2tg150p': 5264,
 'tonexs': 6969,
 'subscription': 6564,
 'renewed': 5686,
 '50': 534,
 'choose': 1804,
 '10': 257,
 'more': 4581,
 'polys': 5288,
 'clubzed': 1862,
 'co': 1871,
 'uk': 7126,
 'billing': 1357,
 'diet': 2307,
 'flew': 2886,
 'window': 7529,
 'dramatic': 2443,
 'schools': 5935,
 'already': 921,
 'closed': 1852,
 'apparently': 1020,
 'drive': 2458,
 'inch': 3662,
 'ref': 5634,
 'r836': 5528,
 'tone': 6965,
 'arrive': 1080,
 '09065069154': 220,
 'awarded': 1166,
 'city': 1821,
 'could': 2034,
 'win': 7527,
 '200': 346,
 'summer': 6593,
 'spree': 6413,
 'wk': 7564,
 'store': 6502,
 '88039': 697,
 'skilgme': 6196,
 'tscs087147403231winawk': 7070,
 '50perwksub': 541,
 'neva': 4749,
 'hostel': 3521,
 'ard': 1050,
 'start': 6448,
 'whole': 7504,
 'appreciated': 1033,
 'dad': 2150,
 'having': 3372,
 'map': 4355,
 'semi': 6004,
 'argument': 1061,
 'apart': 1011,
 'bank': 1216,
 'xxxmobilemovieclub': 7668,
 'use': 7218,
 'credit': 2074,
 'click': 1845,
 'wap': 7385,
 'http': 3551,
 'qjkgighjjgcbl': 5505,
 'sir': 6178,
 'waiting': 7359,
 '08714712388': 118,
 '10am': 267,
 '7pm': 629,
 'cost': 2025,
 '10p': 269,
 'esplanade': 2648,
 'giving': 3154,
 'lift': 4118,
 'smile': 6249,
 'hppnss': 3545,
 'drop': 2464,
 'tear': 6737,
 'sorrow': 6325,
 'heart': 3389,
 'life': 4113,
 'mine': 4489,
 'wil': 7521,
 'forevr': 2942,
 'goodfriend': 3190,
 'gandhipuram': 3071,
 'walk': 7363,
 'cross': 2086,
 'cut': 2135,
 'road': 5790,
 'right': 5771,
 'street': 6514,
 'turn': 7085,
 'first': 2868,
 'awesome': 1168,
 'minute': 4499,
 'bluray': 1412,
 'player': 5231,
 'paper': 5065,
 'ended': 2586,
 'ago': 867,
 'copied': 2010,
 'haf': 3302,
 'study': 6538,
 'panasonic': 5056,
 'bluetoothhdset': 1409,
 'nokia': 4801,
 'motorola': 4598,
 'doublemins': 2425,
 'doubletxt': 2427,
 'orange': 4975,
 'contract': 1995,
 'mobileupd8': 4546,
 '08000839402': 50,
 '2optout': 408,
 'fucking': 3031,
 'chickened': 1781,
 'messaged': 4457,
 'would': 7620,
 'woould': 7594,
 'buzz': 1590,
 'didn': 2302,
 'word': 7597,
 'hot': 3522,
 '08707509020': 88,
 '20p': 354,
 'ntt': 4846,
 'ltd': 4257,
 'box': 1456,
 '1327': 290,
 'croydon': 2089,
 'cr9': 2055,
 '5wb': 562,
 '0870': 70,
 'national': 4699,
 'oops': 4951,
 'died': 2306,
 'even': 2663,
 'better': 1334,
 'hmph': 3467,
 'head': 3378,
 'big': 1352,
 'baller': 1207,
 'wonders': 7588,
 '7th': 630,
 '6th': 604,
 'style': 6548,
 '5th': 561,
 '4th': 523,
 'personality': 5157,
 '3rd': 464,
 'nature': 4702,
 '2nd': 404,
 '1st': 335,
 'lovely': 4236,
 'used': 7219,
 'usf': 7221,
 'man': 4340,
 'lot': 4219,
 'stoners': 6489,
 'accordingly': 779,
 'repeat': 5695,
 'performance': 5142,
 'calculated': 1605,
 'current': 2124,
 'period': 5147,
 'small': 6239,
 'house': 3531,
 'beautiful': 1277,
 'hunt': 3573,
 'waste': 7397,
 'wonderful': 7586,
 'goodmorning': 3193,
 'callin': 1621,
 'bruv': 1537,
 'pandy': 5057,
 'joined': 3856,
 '4w': 529,
 'technologies': 6743,
 'reach': 5576,
 'ten': 6762,
 'centre': 1712,
 'ttyl': 7073,
 'may': 4402,
 'dismay': 2357,
 'many': 4354,
 'times': 6901,
 'wnt': 7575,
 'buy': 1584,
 'bmw': 1413,
 'urgently': 7204,
 'vry': 7330,
 'hv': 3585,
 'shortage': 6108,
 'lacs': 4011,
 'source': 6341,
 'arng': 1071,
 'dis': 2340,
 'prob': 5414,
 'thanx': 6804,
 '2day': 382,
 'goodmate': 3192,
 'rite': 5787,
 'sary': 5901,
 'asusual': 1117,
 'cheered': 1764,
 'franyxxxxx': 2978,
 'looks': 4206,
 'scrumptious': 5956,
 'daddy': 2151,
 'wants': 7384,
 'eat': 2520,
 'darlin': 2169,
 'im': 3633,
 'missin': 4513,
 'time': 6900,
 'jess': 3836,
 'xx': 7665,
 '2p': 409,
 'germany': 3122,
 '08448350055': 64,
 'bt': 1542,
 'planettalkinstant': 5223,
 'info': 3690,
 'opt': 4965,
 'entry': 2618,
 'textpod': 6793,
 '40gb': 476,
 'ipod': 3752,
 '250': 368,
 'cash': 1679,
 'pod': 5271,
 '84128': 671,
 'ts': 7067,
 'custcare': 2130,
 '08712405020': 109,
 'mob': 4541,
 'nok': 4800,
 '87021': 686,
 'txtin': 7104,
 '150p': 304,
 'reply': 5703,
 'hl': 3459,
 '4info': 516,
 'person': 5154,
 'gonna': 3187,
 'ac': 764,
 'sptv': 6416,
 'jersey': 3835,
 'devils': 2281,
 'detroit': 2276,
 'red': 5629,
 'wings': 7535,
 'hockey': 3471,
 'correct': 2018,
 'incorrect': 3672,
 'end': 2585,
 'feel': 2799,
 'lennon': 4090,
 'engin': 2598,
 'sis': 6180,
 'arts': 1085,
 'weekend': 7444,
 'spanish': 6355,
 '09050000332': 162,
 'rstm': 5831,
 'sw7': 6638,
 '3ss': 465,
 '150ppm': 308,
 'rajini': 5542,
 'under': 7143,
 'standing': 6440,
 'blimey': 1392,
 'exercise': 2702,
 'hmm': 3463,
 'intro': 3733,
 'covers': 2050,
 'energy': 2593,
 'trends': 7043,
 'pros': 5454,
 'cons': 1976,
 'brief': 1506,
 'description': 2264,
 'nuclear': 4848,
 'fusion': 3052,
 'history': 3451,
 'iter': 3779,
 'jet': 3838,
 'half': 3312,
 'pages': 5044,
 'enjoy': 2601,
 'yet': 7703,
 'ya': 7677,
 'sapna': 5893,
 'aunty': 1146,
 ...}

In [20]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(7757,))

In [27]:
X_train_np[0][3334]

np.int64(1)

In [21]:
np.where(X_train_np[0]!=0)

(array([3334, 3420, 6753, 6811, 6936, 7064, 7481]),)

In [29]:
X_train_np[0][3334]

np.int64(1)

<h3>Train the naive bayes model</h3>

In [30]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [31]:
X_test_cv = v.transform(X_test)

<h3>Evaluate Performance</h3>

In [33]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       961
           1       0.97      0.93      0.95       154

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115

In [34]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

<h3>Train the model using sklearn pipeline and reduce number of lines of code</h3>

In [35]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [36]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [37]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       961
           1       0.97      0.93      0.95       154

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115